# Generated by Django 5.2 on 2025-05-05 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Дома",
                        help_text="Место, в котором необходимо выполнять привычку.",
                        max_length=250,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Время, когда необходимо выполнять привычку.",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка.",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки.",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания в днях.",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        help_text="Чем пользователь должен себя вознаградить после выполнения.",
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки.",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "publicity_sign",
                    models.BooleanField(
                        default=True,
                        help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите создателя привычки.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Привычка",),
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
