# Generated by Django 5.2 on 2025-04-25 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Периодичность выполнения привычки для напоминания в днях.",
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="Время, когда необходимо выполнять привычку.",
                verbose_name="Время",
            ),
        ),
    ]
