# Generated by Django 5.2 on 2025-04-30 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_periodicity_alter_habit_related_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Время, когда необходимо выполнять привычку.",
                verbose_name="Время",
            ),
        ),
    ]
